name: 每日签到2

on:
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  daily-checkin:
    runs-on: ubuntu-latest

    steps:
    - name: 发送签到请求
      run: |
        curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${{ secrets.ARAINYUN_API_KEY }}" \
          -d '{"task_name": "每日签到"}' \
          https://api.v2.rainyun.com/user/reward/tasks
